/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    CarouselItem: typeof import('./src/components/CarouselItem.vue')['default']
    component: typeof import('vue')['component']
    IconSprite: typeof import('./src/components/UI/IconSprite.vue')['default']
    Modal: typeof import('./src/components/UI/Modal.vue')['default']
    PersonInfo: typeof import('./src/components/PersonInfo.vue')['default']
    Preloader: typeof import('./src/components/UI/Preloader.vue')['default']
  }
}
